title: Franklin Heng
logo: assets/imgs/profile_pic.jpeg
description: "Computer Vision Engineer<br>Prev: <a href='https://www.linkedin.com/company/runningtide/posts/?feedView=all' target='_blank'>Running Tide</a>, <a href='https://scvrb-core.ucsf.edu/~fahy/' target='_blank'>UCSF</a>"
show_downloads: false 
theme: jekyll-theme-minimal
