title: Franklin Heng
logo: assets/imgs/profile_pic.jpeg
description: Computer Vision Engineer, Prev [Running Tide](https://www.linkedin.com/company/runningtide/posts/?feedView=all)
show_downloads: false 
theme: jekyll-theme-minimal
