title: Franklin Heng
logo: assets/imgs/profile_pic.jpeg
description: "Computer Vision Engineer,&nbsp;Prev <a href='https://www.linkedin.com/company/running-tide/' target='_blank'>Running Tide</a>"
show_downloads: false 
theme: jekyll-theme-minimal
